version: 2
updates:
  - package-ecosystem: 'gomod' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'gomod' # See documentation for possible values
    directory: '/internal/tools' # Location of package manifests
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'github-actions'
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: '/'
    schedule:
      interval: 'weekly'
